### ISSUE TITLE
想下载做预加载的功能

### ISSUE THREAD

**Issue by BaiCanLin** [swtlovewtt/WTRequestCenter#20]
请问想做带有进度条下载的功能怎么实现的呢

**Comment by BaiCanLin** [comment]
可以添加多一个枚举，如果有网络就直接网络，如果没有网络就直接本地

**Comment by swtlovewtt** [comment]
进度条的问题其实在测试里面有，然后你说的这个枚举我觉得不好，不予采纳。
谢谢你提建议。
