### ISSUE TITLE
为什么https 会请求失败呢

### ISSUE THREAD

**Issue by BaiCanLin** [swtlovewtt/WTRequestCenter#21]
我发现 https 会请求失败的

**Comment by swtlovewtt** [comment]
请求内容是什么？我试试

**Comment by BaiCanLin** [comment]
//        NSString *urlString = [[NSString stringWithFormat:@"%@?%@",request.URL,query] stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
        NSString *urlString = [[NSString stringWithFormat:@"%@%@",request.URL,query] stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];    我把 ？ 这个问号去掉了就行了

**Comment by BaiCanLin** [comment]
有空私聊一下我，我发网站给你

**Comment by swtlovewtt** [comment]
发我邮箱吧，我会测的

**Comment by swtlovewtt** [comment]
已经修复了，你可以下载最新版本测试一下
