### ISSUE TITLE
对于 https 支持不好

### ISSUE THREAD

**Issue by BaiCanLin** [swtlovewtt/WTRequestCenter#22]
WTRequestCenterCachePolicyCacheAndWeb 如果使用这个在某些情况下会出现重复数据的,使用WTRequestCenterCachePolicyCacheAndRefresh一般情况下是正常的，但是对于https的接口请求，这个缓存是有，但是永远不会去更新数据了

**Comment by swtlovewtt** [comment]
谢谢，私信告诉我怎么测试你的借口？

**Comment by swtlovewtt** [comment]
问题解决了不？
