### ISSUE TITLE
发现了个小问题。UserAgent的

### ISSUE THREAD

**Issue by shihw** [swtlovewtt/WTRequestCenter#24]
我发现使用UIWebView+WTRequestCenter.h这个类时候

系统的UserAgent被改变了。导致了手机网页变成了电脑网页。这个该怎么解决下呢。

http://www.enhanceie.com/ua.aspx 我用的这个网站测试的UserAgent。

![f09bb966-1828-478d-976f-629a636a70fb](https://cloud.githubusercontent.com/assets/7566008/7579624/2f122724-f899-11e4-8761-611c7a649cff.png)

**Comment by shihw** [comment]
![Uploading F09BB966-1828-478D-976F-629A636A70FB.png…]()

**Comment by swtlovewtt** [comment]
有意思的问题,通过这个方法可以重置全局的User-Agent
[[WTURLRequestSerialization sharedRequestSerialization] setValue:@"value"
                                                  forHTTPHeaderField:@"User-Agent"];

**Comment by shihw** [comment]
有没有直接使用系统的。并非手工对其设置？因为每个手机应该User-Agent不太一样的。

**Comment by swtlovewtt** [comment]
不好意思,我吧User-Agent给改了.....你把这个值改成nil试试吧

**Comment by shihw** [comment]
好的。
